#!/usr/bin/env python
# coding: utf-8

# In[ ]:


#Column Names, list of column names used during processing
col_dic = {    
    'file_name': 'file_name',
    'key_name' :'key_name',
    'area' : 'area',
    'radius' : 'radius',
    'perimeter': 'perimeter',
    'spot_id' : 'spot_id',
    'frame': 'frame',
    'quality' : 'quality',
    'solidity' : 'solidity',
    'donor_mean' : 'donor_mean',
    'donor_min' : 'donor_min',
    'donor_max' : 'donor_max',
    'donor_std' : 'donor_std',
    'acceptor_mean' : 'acceptor_mean',
    'acceptor_min' : 'acceptor_min',
    'acceptor_max' : 'acceptor_max',
    'acceptor_std' : 'acceptor_std',
    'directAcceptor_mean' : 'directAcceptor_mean',
    'directAcceptor_min' : 'directAcceptor_min',
    'directAcceptor_max' : 'directAcceptor_max',
    'directAcceptor_std' : 'directAcceptor_std',
    'mcherry_mean' : 'mcherry_mean',
    'mcherry_min' : 'mcherry_min',
    'mcherry_max' : 'mcherry_max',
    'mcherry_std' : 'mcherry_std',
    'efret' : 'efret',
    'corr_acc' : 'corrected_accecptor',
    'bleedthough' : 'bleedthrough',
    'crossexcitation' : 'crossexcitation',
    'construct' : 'construct',
    'experiment_parameter' : 'experiment_parameter',
    'experiment_condition' : 'experiment_condition',
    'well' : 'well',
    'intrawell_replicate' : 'intrawell_replicate',
    'time_interval' : 'time_interval (hr)',
    'thresholding_type' : 'thresholding_type',
    'model_used' :  'model',
    'thresholding_used' :'thresholding',
    'date_processed' : 'date_processed',
    'experiment_date' : 'experiment_date',
    'file_name' : 'file_name',
    'imaging_type' : 'imaging_type',
    'led_1_intensity' : 'led_1_intensity',
    'led_2_intensity' : 'led_2_intensity',
    'camera_1_shutter' : 'camera_1_shutter (ms)',
    'camera_2_shutter' : 'camera_2_shutter (ms)',
    'construct' : 'construct',
    'passage' : 'passage',
}
